Revert "Catch non-utf8 and convert it to utf8 inside create_submit_request() to prevent"
This reverts commit 518229067c9815e4f671469295266d4fd6cbf6c4.
Doesn't solve your issue:

    >>> unicode("!§").encode("utf8")
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)

Fix pending...