Fix how types are compared in OscOptions.set_value_from_string()
Some python versions require '==' instead of 'is' operator, otherwise we get
TypeError: Field 'http_headers' has type 'typing.List[osc.conf.HttpHeader]'. Cannot assign a value with type 'str'.