Require at least PyYAML 3.14
... due to usage of sort_keys

TypeError: dump_all() got an unexpected keyword argument 'sort_keys'

Signed-off-by: Olaf Hering <olaf@aepfle.de>